data <- read.table("household_power_consumption.txt", header=TRUE, sep=";")
data$Date <- as.Date(data$Date, format = "%d/%m/%Y")
Data <- subset(data, subset = (Date >= "2007-02-01" & Date <= "2007-02-02"))
datetime <- strptime(paste(Data$Date,Data$Time),format = "%Y-%m-%d %H:%M:%S")
globalActivePower <- as.numeric(Data$Global_active_power)
plot(datetime, globalActivePower, type="l", xlab="", ylab="Global Active Power (kilowatts)")
dev.copy(png,file="plot2.png",height=480,width=480)
dev.off()