data <- read.table("household_power_consumption.txt", header=TRUE, sep=";")
data$Date <- as.Date(data$Date, format = "%d/%m/%Y")
Data <- subset(data, subset = (Date >= "2007-02-01" & Date <= "2007-02-02"))
datetime <- strptime(paste(Data$Date,Data$Time),format = "%Y-%m-%d %H:%M:%S")
plot(datetime, Data$Sub_metering_1, type="l", ylab="energy submetering")
lines(datetime,Data$Sub_metering_2,col="Red")
lines(datetime,Data$Sub_metering_3,col="Blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lwd=2, col=c("black", "red", "blue"))
dev.copy(png,file="plot3.png",height=480,width=480)
dev.off()